# Generated by Django 4.1.3 on 2022-11-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_pic',
            field=models.ImageField(default=None, upload_to='users_posts'),
        ),
    ]
