# Generated by Django 4.1.3 on 2022-11-03 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0002_post_upload_pic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="upload_pic", new_name="image",
        ),
        migrations.AddField(
            model_name="post",
            name="date_publication",
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="post", name="price", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
