# Generated by Django 4.1.3 on 2022-11-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_rename_upload_pic_post_image_post_date_publication_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_publication",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
