# Generated by Django 4.1 on 2022-11-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0009_alter_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="price", field=models.IntegerField(),
        ),
    ]
