# Generated by Django 4.1 on 2022-11-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_alter_post_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(max_length=1000),
        ),
    ]
