# Generated by Django 4.1 on 2022-11-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0011_alter_post_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
