# Generated by Django 4.1 on 2022-11-25 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0012_alter_post_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera", models.TextField(max_length=256)),
                ("model", models.TextField(max_length=256)),
                ("aperture", models.FloatField(max_length=256)),
                ("shutter_speed", models.FloatField(max_length=256)),
                ("focal_length", models.FloatField(max_length=256)),
                ("iso", models.IntegerField(max_length=256)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="post.post"
                    ),
                ),
            ],
        ),
    ]
