# Generated by Django 4.1 on 2022-11-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0014_post_aperture_post_camera_post_exif_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="shutter_speed",
            field=models.CharField(default=None, editable=False, max_length=100),
        ),
    ]
