# Generated by Django 4.1 on 2022-11-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0016_alter_post_iso"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="iso",),
    ]
