# Generated by Django 4.1 on 2022-11-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0017_remove_post_iso"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="iso_number",
            field=models.CharField(default=None, editable=False, max_length=100),
        ),
    ]
