# Generated by Django 4.1 on 2022-11-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0018_post_iso_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="iso_number",
            field=models.CharField(
                blank=True, default=None, editable=False, max_length=100, null=True
            ),
        ),
    ]
