# Generated by Django 4.1 on 2022-11-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0019_alter_post_iso_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="iso_number",),
    ]
