# Generated by Django 4.1 on 2022-11-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0021_post_iso_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="aperture",
            field=models.FloatField(
                blank=True, default=None, editable=False, max_length=100
            ),
        ),
    ]
