# Generated by Django 4.1 on 2022-11-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0022_alter_post_aperture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="aperture",
            field=models.FloatField(
                blank=True, default=None, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="focal_length",
            field=models.CharField(default=None, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="iso_number",
            field=models.CharField(
                blank=True, default=None, editable=False, max_length=100, null=True
            ),
        ),
    ]
