# Generated by Django 4.1 on 2022-11-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0023_alter_post_aperture_alter_post_focal_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="camera",
            field=models.TextField(
                blank=True, default=None, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="focal_length",
            field=models.CharField(
                blank=True, default=None, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="model",
            field=models.TextField(
                blank=True, default=None, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="shutter_speed",
            field=models.CharField(
                blank=True, default=None, editable=False, max_length=100, null=True
            ),
        ),
    ]
