# Generated by Django 4.1 on 2022-11-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_order_orderitem_shippingmodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="item_type",
            field=models.CharField(
                choices=[("DIGITAL", "Digital"), ("PRINT", " Print")],
                default="DIGITAL",
                max_length=7,
            ),
        ),
    ]
