# Generated by Django 4.1 on 2022-11-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_orderitem_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="item_type",
            field=models.CharField(default=None, max_length=7),
        ),
    ]
